-- ==========================================
-- คำสั่งล้างตารางเดิม (Overwrite / Reset)
-- ==========================================
DROP TABLE IF EXISTS public.form_responses CASCADE;
DROP TABLE IF EXISTS public.form_submissions CASCADE;
DROP TABLE IF EXISTS public.form_fields CASCADE;
DROP TABLE IF EXISTS public.forms CASCADE;
DROP TABLE IF EXISTS public.broadcast_history CASCADE;
DROP TABLE IF EXISTS public.audiences CASCADE;
DROP TABLE IF EXISTS public.user_tags CASCADE;
DROP TABLE IF EXISTS public.tags CASCADE;
DROP TABLE IF EXISTS public.narrowcast_templates CASCADE;
DROP TABLE IF EXISTS public.group_members CASCADE;
DROP TABLE IF EXISTS public.line_groups CASCADE;
DROP TABLE IF EXISTS public.system_settings CASCADE;
DROP TABLE IF EXISTS public.chat_history CASCADE;
DROP TABLE IF EXISTS public.keyword_permissions CASCADE;
DROP TABLE IF EXISTS public.user_profiles CASCADE;
DROP TABLE IF EXISTS public.keywords CASCADE;
DROP TABLE IF EXISTS public.rich_menus CASCADE;

-- ==========================================
-- เริ่มต้นสร้างตารางใหม่
-- ==========================================

create table public.rich_menus (
  id bigint generated by default as identity not null,
  name text not null,
  rich_menu_id text not null,
  image_url text null,
  description text null,
  created_at timestamp with time zone null default timezone ('utc'::text, now()),
  constraint rich_menus_pkey primary key (id),
  constraint rich_menus_rich_menu_id_key unique (rich_menu_id)
) TABLESPACE pg_default;

create table public.keywords (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  keyword text null,
  reply_flex text null,
  reply_text text null,
  reply_image text null,
  reply_template text null,
  require_vip boolean null,
  reply_richmenu text null,
  reply_postback text null,
  reply_prompt text null,
  startdatetime text null,
  enddatetime text null,
  constraint keywords_pkey primary key (id)
) TABLESPACE pg_default;

create table public.user_profiles (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "userId" text not null,
  "displayName" text null,
  "pictureUrl" text null,
  "statusMessage" text null,
  status text null,
  updated_at timestamp without time zone not null,
  role text null,
  ai_enabled boolean null default true,
  ai_status boolean null default true,
  constraint user_profiles_pkey primary key ("userId")
) TABLESPACE pg_default;

create table public.keyword_permissions (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  "userId" text null,
  keyword text null,
  vip boolean null,
  constraint keyword_permissions_pkey primary key (id)
) TABLESPACE pg_default;


create table public.chat_history (
  id bigint generated by default as identity not null,
  user_id text not null,
  role text not null,
  message text not null,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint chat_history_pkey primary key (id),
  constraint chat_history_role_check check (
    (
      role = any (array['user'::text, 'assistant'::text])
    )
  )
) TABLESPACE pg_default;

create index IF not exists chat_history_user_id_idx on public.chat_history using btree (user_id) TABLESPACE pg_default;


create index if not exists chat_history_user_id_idx on chat_history (user_id);


create table public.system_settings (
  key text not null,
  value jsonb not null,
  constraint system_settings_pkey primary key (key)
) TABLESPACE pg_default;


create table public.line_groups (
  group_id text primary key,
  joined_at timestamp with time zone not null default now()
) TABLESPACE pg_default;


create table public.group_members (
  group_id text not null,
  user_id text not null,
  joined_at timestamp with time zone not null default now(),
  constraint group_members_pkey primary key (group_id, user_id),
  constraint group_members_group_id_fkey foreign key (group_id) references line_groups(group_id) on delete cascade
) TABLESPACE pg_default;


create table public.user_tags (
  id bigint generated by default as identity not null,
  tag_name text not null,
  user_id text not null,
  created_at timestamp with time zone not null default now(),
  constraint user_tags_pkey primary key (id),
  constraint user_tags_user_id_fkey foreign key ("user_id") references user_profiles ("userId") on delete cascade,
  unique (user_id, tag_name)
);


create index if not exists user_tags_tag_name_idx on public.user_tags(tag_name);
create index if not exists user_tags_user_id_idx on public.user_tags(user_id);


create table public.narrowcast_templates (
  id bigint generated by default as identity not null,
  name text not null,
  messages jsonb not null,
  created_at timestamp with time zone not null default now(),
  constraint narrowcast_templates_pkey primary key (id)
);

-- ==========================================
-- สร้างตารางที่จำเป็นเพิ่มเติม (หากยังไม่มี)
-- ==========================================

CREATE TABLE IF NOT EXISTS public.tags (
  id SERIAL PRIMARY KEY,
  name TEXT UNIQUE NOT NULL,
  color TEXT DEFAULT '#6366f1',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.audiences (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  description TEXT,
  criteria JSONB DEFAULT '{}',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.broadcast_history (
  id SERIAL PRIMARY KEY,
  title TEXT,
  message_content JSONB NOT NULL,
  target_count INTEGER DEFAULT 0,
  status TEXT DEFAULT 'pending', 
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. ตารางประวัติบรอดแคสต์
DROP POLICY IF EXISTS "Enable all for anon on broadcast_history" ON public.broadcast_history;
CREATE POLICY "Enable all for anon on broadcast_history" ON public.broadcast_history FOR ALL TO anon USING (true) WITH CHECK (true);

-- ==========================================
-- ระบบ DYNAMIC FORM BUILDER
-- ==========================================

-- 1. ตารางฟอร์มหลัก
CREATE TABLE IF NOT EXISTS public.forms (
  id SERIAL PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  keyword TEXT UNIQUE NOT NULL, 
  is_active BOOLEAN DEFAULT TRUE,
  success_message TEXT DEFAULT 'ขอบคุณสำหรับข้อมูลครับ 🙏',
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. ตารางฟิลด์หรือคำถามในฟอร์ม
CREATE TABLE IF NOT EXISTS public.form_fields (
  id SERIAL PRIMARY KEY,
  form_id INTEGER REFERENCES public.forms(id) ON DELETE CASCADE,
  label TEXT NOT NULL,      
  type TEXT DEFAULT 'text', 
  options JSONB DEFAULT '[]', 
  order_index INTEGER DEFAULT 0,
  is_required BOOLEAN DEFAULT TRUE
);

-- 3. ตารางบันทึกการส่งฟอร์ม (Submission)
CREATE TABLE IF NOT EXISTS public.form_submissions (
  id SERIAL PRIMARY KEY,
  form_id INTEGER REFERENCES public.forms(id) ON DELETE CASCADE,
  user_id TEXT REFERENCES public.user_profiles("userId") ON DELETE CASCADE,
  current_field_index INTEGER DEFAULT 0, 
  status TEXT DEFAULT 'pending', 
  created_at TIMESTAMPTZ DEFAULT NOW(),
  completed_at TIMESTAMPTZ
);

-- 4. ตารางเก็บคำตอบ
CREATE TABLE IF NOT EXISTS public.form_responses (
  id SERIAL PRIMARY KEY,
  submission_id INTEGER REFERENCES public.form_submissions(id) ON DELETE CASCADE,
  field_id INTEGER REFERENCES public.form_fields(id) ON DELETE CASCADE,
  response_value TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- บังคับสร้าง Unique Constraint เพื่อแก้ปัญหาคำตอบซ้ำเมื่อกดย้อนกลับ
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'unique_sub_field') THEN
        ALTER TABLE public.form_responses ADD CONSTRAINT unique_sub_field UNIQUE(submission_id, field_id);
    END IF;
END $$;

-- ==========================================
-- ตรวจสอบและเปิดใช้งาน RLS ให้กับทุกตาราง (บรรทัดสุดท้ายเพื่อให้ครอบคลุมทุกตารางข้างต้น)
-- ==========================================

DO $$ 
DECLARE 
    t text;
BEGIN
    FOR t IN 
        SELECT table_name 
        FROM information_schema.tables 
        WHERE table_schema = 'public' 
        AND table_type = 'BASE TABLE'
    LOOP
        -- เปิด RLS
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY;', t);
        
        -- ลบ Policy เดิม (ถ้ามี)
        EXECUTE format('DROP POLICY IF EXISTS %I ON public.%I;', 'Enable all for anon on ' || t, t);
        
        -- สร้าง Policy ใหม่ให้ anon จัดการได้ทุกอย่าง (ALL)
        EXECUTE format('CREATE POLICY %I ON public.%I FOR ALL TO anon USING (true) WITH CHECK (true);', 'Enable all for anon on ' || t, t);
    END LOOP;
END $$;

-- 💡 หมายเหตุ: การวางไว้ท้ายสุดจะทำให้ทุกตารางที่ถูกสร้างในไฟล์นี้ได้รับ Policy โดยอัตโนมัติ

-- การแก้ไขข้อมูลแอดมินจะทำผ่าน Edge Function อยู่แล้ว ไม่ต้องเพิ่ม Policy INSERT/UPDATE สำหรับ anon


-- นโยบายสำหรับอนุญาตให้เข้าถึง Storage ของ Supabase ผ่าน Client (anon key)
-- ดูรายชื่อ Bucket (listBuckets)
drop policy if exists "Allow public viewing of buckets" on storage.buckets;
create policy "Allow public viewing of buckets" on storage.buckets for select using (true);

-- อนุญาตให้อ่าน/เขียน/ลบ ไฟล์ในตาราง Objects (list, remove)
drop policy if exists "Allow public all on objects" on storage.objects;
create policy "Allow public all on objects" on storage.objects for all using (true) with check (true);